"""multiplatform social schema

Revision ID: 20260727_0001
Revises: 
Create Date: 2026-07-27 11:08:00.560988
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = '20260727_0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_accounts',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('platform', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=500), nullable=True),
    sa.Column('profile_url', sa.Text(), nullable=True),
    sa.Column('account_hash', sa.String(length=128), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('platform_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("platform IN ('facebook', 'tiktok', 'threads', 'manual')", name='ck_social_accounts_platform'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'account_hash', name='uq_social_accounts_platform_hash')
    )
    op.create_index(op.f('ix_social_accounts_account_hash'), 'social_accounts', ['account_hash'], unique=False)
    op.create_index(op.f('ix_social_accounts_external_id'), 'social_accounts', ['external_id'], unique=False)
    op.create_index(op.f('ix_social_accounts_platform'), 'social_accounts', ['platform'], unique=False)
    op.create_index(op.f('ix_social_accounts_username'), 'social_accounts', ['username'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('platform', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('source_kind', sa.String(length=40), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('handle', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=80), nullable=False),
    sa.Column('access_basis', sa.String(length=80), nullable=False),
    sa.Column('authorization_status', sa.String(length=40), nullable=False),
    sa.Column('collection_method', sa.String(length=80), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('crawl_frequency', sa.String(length=40), nullable=False),
    sa.Column('lookback_hours', sa.Integer(), nullable=False),
    sa.Column('comment_policy', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('privacy', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('owner', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('platform_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("platform IN ('facebook', 'tiktok', 'threads', 'manual')", name='ck_sources_platform'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'external_id', name='uq_sources_platform_external_id')
    )
    op.create_index(op.f('ix_sources_authorization_status'), 'sources', ['authorization_status'], unique=False)
    op.create_index(op.f('ix_sources_external_id'), 'sources', ['external_id'], unique=False)
    op.create_index(op.f('ix_sources_handle'), 'sources', ['handle'], unique=False)
    op.create_index(op.f('ix_sources_platform'), 'sources', ['platform'], unique=False)
    op.create_index('ix_sources_platform_kind_enabled', 'sources', ['platform', 'source_kind', 'enabled'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('auth_sessions',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_sessions_expires_at'), 'auth_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_auth_sessions_token_hash'), 'auth_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_table('platform_connections',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('platform', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('auth_method', sa.String(length=40), nullable=False),
    sa.Column('profile_dir', sa.Text(), nullable=False),
    sa.Column('login_url', sa.Text(), nullable=False),
    sa.Column('browser_process_id', sa.Integer(), nullable=True),
    sa.Column('last_connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('connection_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("platform IN ('facebook', 'tiktok', 'threads', 'manual')", name='ck_platform_connections_platform'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'platform', name='uq_connection_user_platform')
    )
    op.create_index(op.f('ix_platform_connections_platform'), 'platform_connections', ['platform'], unique=False)
    op.create_index(op.f('ix_platform_connections_status'), 'platform_connections', ['status'], unique=False)
    op.create_index(op.f('ix_platform_connections_user_id'), 'platform_connections', ['user_id'], unique=False)
    op.create_table('oauth_states',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('connection_id', sa.String(length=120), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('state_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['platform_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_states_connection_id'), 'oauth_states', ['connection_id'], unique=False)
    op.create_index(op.f('ix_oauth_states_expires_at'), 'oauth_states', ['expires_at'], unique=False)
    op.create_index(op.f('ix_oauth_states_provider'), 'oauth_states', ['provider'], unique=False)
    op.create_index(op.f('ix_oauth_states_state_hash'), 'oauth_states', ['state_hash'], unique=True)
    op.create_index(op.f('ix_oauth_states_user_id'), 'oauth_states', ['user_id'], unique=False)
    op.create_table('run_configurations',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('connection_id', sa.String(length=120), nullable=False),
    sa.Column('source_id', sa.String(length=120), nullable=False),
    sa.Column('max_posts', sa.Integer(), nullable=False),
    sa.Column('max_comments_per_post', sa.Integer(), nullable=False),
    sa.Column('lookback_hours', sa.Integer(), nullable=False),
    sa.Column('include_replies', sa.Boolean(), nullable=False),
    sa.Column('filters', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=40), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['platform_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'connection_id', 'source_id', name='uq_run_configurations_user_connection_source')
    )
    op.create_index(op.f('ix_run_configurations_connection_id'), 'run_configurations', ['connection_id'], unique=False)
    op.create_index(op.f('ix_run_configurations_is_archived'), 'run_configurations', ['is_archived'], unique=False)
    op.create_index(op.f('ix_run_configurations_source_id'), 'run_configurations', ['source_id'], unique=False)
    op.create_index(op.f('ix_run_configurations_user_id'), 'run_configurations', ['user_id'], unique=False)
    op.create_table('collection_jobs',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('run_configuration_id', sa.String(length=120), nullable=False),
    sa.Column('connection_id', sa.String(length=120), nullable=False),
    sa.Column('source_id', sa.String(length=120), nullable=False),
    sa.Column('platform', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('trigger', sa.String(length=40), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('posts_collected', sa.Integer(), nullable=False),
    sa.Column('comments_collected', sa.Integer(), nullable=False),
    sa.Column('replies_collected', sa.Integer(), nullable=False),
    sa.Column('records_inserted', sa.Integer(), nullable=False),
    sa.Column('duplicates_skipped', sa.Integer(), nullable=False),
    sa.Column('output_path', sa.Text(), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('result_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("platform IN ('facebook', 'tiktok', 'threads', 'manual')", name='ck_collection_jobs_platform'),
    sa.ForeignKeyConstraint(['connection_id'], ['platform_connections.id'], ),
    sa.ForeignKeyConstraint(['run_configuration_id'], ['run_configurations.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_jobs_connection_id'), 'collection_jobs', ['connection_id'], unique=False)
    op.create_index(op.f('ix_collection_jobs_platform'), 'collection_jobs', ['platform'], unique=False)
    op.create_index(op.f('ix_collection_jobs_run_configuration_id'), 'collection_jobs', ['run_configuration_id'], unique=False)
    op.create_index(op.f('ix_collection_jobs_source_id'), 'collection_jobs', ['source_id'], unique=False)
    op.create_index(op.f('ix_collection_jobs_status'), 'collection_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_collection_jobs_user_id'), 'collection_jobs', ['user_id'], unique=False)
    op.create_index('ix_collection_jobs_user_status_created', 'collection_jobs', ['user_id', 'status', 'created_at'], unique=False)
    op.create_table('raw_items',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('owner_user_id', sa.String(length=120), nullable=True),
    sa.Column('source_id', sa.String(length=120), nullable=False),
    sa.Column('collection_job_id', sa.String(length=120), nullable=True),
    sa.Column('platform', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('item_type', sa.String(length=40), nullable=False),
    sa.Column('parent_external_id', sa.String(length=255), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('raw_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('permalink', sa.Text(), nullable=True),
    sa.Column('import_batch_id', sa.String(length=120), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("item_type IN ('post', 'comment', 'reply')", name='ck_raw_items_item_type'),
    sa.CheckConstraint("platform IN ('facebook', 'tiktok', 'threads', 'manual')", name='ck_raw_items_platform'),
    sa.ForeignKeyConstraint(['collection_job_id'], ['collection_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_id', 'source_id', 'content_hash', name='uq_raw_items_owner_source_content_hash')
    )
    op.create_index(op.f('ix_raw_items_collected_at'), 'raw_items', ['collected_at'], unique=False)
    op.create_index(op.f('ix_raw_items_collection_job_id'), 'raw_items', ['collection_job_id'], unique=False)
    op.create_index(op.f('ix_raw_items_content_hash'), 'raw_items', ['content_hash'], unique=False)
    op.create_index(op.f('ix_raw_items_external_id'), 'raw_items', ['external_id'], unique=False)
    op.create_index(op.f('ix_raw_items_import_batch_id'), 'raw_items', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_raw_items_owner_user_id'), 'raw_items', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_raw_items_parent_external_id'), 'raw_items', ['parent_external_id'], unique=False)
    op.create_index(op.f('ix_raw_items_platform'), 'raw_items', ['platform'], unique=False)
    op.create_index(op.f('ix_raw_items_published_at'), 'raw_items', ['published_at'], unique=False)
    op.create_index('ix_raw_items_source_external', 'raw_items', ['source_id', 'item_type', 'external_id'], unique=False)
    op.create_index(op.f('ix_raw_items_source_id'), 'raw_items', ['source_id'], unique=False)
    op.create_table('content_items',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('raw_item_id', sa.String(length=120), nullable=False),
    sa.Column('owner_user_id', sa.String(length=120), nullable=True),
    sa.Column('source_id', sa.String(length=120), nullable=False),
    sa.Column('platform', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('item_type', sa.String(length=40), nullable=False),
    sa.Column('parent_item_id', sa.String(length=120), nullable=True),
    sa.Column('root_item_id', sa.String(length=120), nullable=True),
    sa.Column('author_id', sa.String(length=120), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('content_language', sa.String(length=20), nullable=True),
    sa.Column('permalink', sa.Text(), nullable=True),
    sa.Column('import_batch_id', sa.String(length=120), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provenance_status', sa.String(length=40), nullable=False),
    sa.Column('platform_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("item_type IN ('post', 'comment', 'reply')", name='ck_content_items_item_type'),
    sa.CheckConstraint("platform IN ('facebook', 'tiktok', 'threads', 'manual')", name='ck_content_items_platform'),
    sa.ForeignKeyConstraint(['author_id'], ['social_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_item_id'], ['content_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['raw_item_id'], ['raw_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['root_item_id'], ['content_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_id', 'source_id', 'item_type', 'external_id', name='uq_content_items_owner_source_type_external'),
    sa.UniqueConstraint('raw_item_id')
    )
    op.create_index(op.f('ix_content_items_author_id'), 'content_items', ['author_id'], unique=False)
    op.create_index(op.f('ix_content_items_collected_at'), 'content_items', ['collected_at'], unique=False)
    op.create_index(op.f('ix_content_items_content_language'), 'content_items', ['content_language'], unique=False)
    op.create_index(op.f('ix_content_items_external_id'), 'content_items', ['external_id'], unique=False)
    op.create_index(op.f('ix_content_items_import_batch_id'), 'content_items', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_content_items_owner_user_id'), 'content_items', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_content_items_parent_item_id'), 'content_items', ['parent_item_id'], unique=False)
    op.create_index(op.f('ix_content_items_platform'), 'content_items', ['platform'], unique=False)
    op.create_index(op.f('ix_content_items_published_at'), 'content_items', ['published_at'], unique=False)
    op.create_index(op.f('ix_content_items_root_item_id'), 'content_items', ['root_item_id'], unique=False)
    op.create_index(op.f('ix_content_items_source_id'), 'content_items', ['source_id'], unique=False)
    op.create_index('ix_content_items_source_type_collected', 'content_items', ['source_id', 'item_type', 'collected_at'], unique=False)
    op.create_index('ix_content_items_user_type_published', 'content_items', ['owner_user_id', 'item_type', 'published_at'], unique=False)
    if op.get_bind().dialect.name == "postgresql":
        op.execute(
            "CREATE INDEX ix_content_items_text_search "
            "ON content_items USING gin (to_tsvector('simple', content_text))"
        )
    op.create_table('content_metric_snapshots',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('content_item_id', sa.String(length=120), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reaction_count', sa.Integer(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('collected_comment_count', sa.Integer(), nullable=False),
    sa.Column('reply_count', sa.Integer(), nullable=False),
    sa.Column('share_count', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('save_count', sa.Integer(), nullable=False),
    sa.Column('platform_metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_item_id', 'observed_at', name='uq_content_metric_item_observed')
    )
    op.create_index('ix_content_metric_item_observed', 'content_metric_snapshots', ['content_item_id', 'observed_at'], unique=False)
    op.create_index(op.f('ix_content_metric_snapshots_content_item_id'), 'content_metric_snapshots', ['content_item_id'], unique=False)
    op.create_index(op.f('ix_content_metric_snapshots_observed_at'), 'content_metric_snapshots', ['observed_at'], unique=False)
    op.create_table('content_topic_matches',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('content_item_id', sa.String(length=120), nullable=False),
    sa.Column('topic_key', sa.String(length=120), nullable=False),
    sa.Column('matched_terms', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('matched_groups', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('filter_version', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_item_id', 'topic_key', name='uq_content_topic_item_topic')
    )
    op.create_index(op.f('ix_content_topic_matches_content_item_id'), 'content_topic_matches', ['content_item_id'], unique=False)
    op.create_index(op.f('ix_content_topic_matches_topic_key'), 'content_topic_matches', ['topic_key'], unique=False)
    op.create_index('ix_content_topic_topic_score', 'content_topic_matches', ['topic_key', 'score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_content_topic_topic_score', table_name='content_topic_matches')
    op.drop_index(op.f('ix_content_topic_matches_topic_key'), table_name='content_topic_matches')
    op.drop_index(op.f('ix_content_topic_matches_content_item_id'), table_name='content_topic_matches')
    op.drop_table('content_topic_matches')
    op.drop_index(op.f('ix_content_metric_snapshots_observed_at'), table_name='content_metric_snapshots')
    op.drop_index(op.f('ix_content_metric_snapshots_content_item_id'), table_name='content_metric_snapshots')
    op.drop_index('ix_content_metric_item_observed', table_name='content_metric_snapshots')
    op.drop_table('content_metric_snapshots')
    op.drop_index('ix_content_items_user_type_published', table_name='content_items')
    op.drop_index('ix_content_items_source_type_collected', table_name='content_items')
    op.drop_index(op.f('ix_content_items_source_id'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_root_item_id'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_published_at'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_platform'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_parent_item_id'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_owner_user_id'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_import_batch_id'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_external_id'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_content_language'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_collected_at'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_author_id'), table_name='content_items')
    if op.get_bind().dialect.name == "postgresql":
        op.drop_index('ix_content_items_text_search', table_name='content_items')
    op.drop_table('content_items')
    op.drop_index(op.f('ix_raw_items_source_id'), table_name='raw_items')
    op.drop_index('ix_raw_items_source_external', table_name='raw_items')
    op.drop_index(op.f('ix_raw_items_published_at'), table_name='raw_items')
    op.drop_index(op.f('ix_raw_items_platform'), table_name='raw_items')
    op.drop_index(op.f('ix_raw_items_parent_external_id'), table_name='raw_items')
    op.drop_index(op.f('ix_raw_items_owner_user_id'), table_name='raw_items')
    op.drop_index(op.f('ix_raw_items_import_batch_id'), table_name='raw_items')
    op.drop_index(op.f('ix_raw_items_external_id'), table_name='raw_items')
    op.drop_index(op.f('ix_raw_items_content_hash'), table_name='raw_items')
    op.drop_index(op.f('ix_raw_items_collection_job_id'), table_name='raw_items')
    op.drop_index(op.f('ix_raw_items_collected_at'), table_name='raw_items')
    op.drop_table('raw_items')
    op.drop_index('ix_collection_jobs_user_status_created', table_name='collection_jobs')
    op.drop_index(op.f('ix_collection_jobs_user_id'), table_name='collection_jobs')
    op.drop_index(op.f('ix_collection_jobs_status'), table_name='collection_jobs')
    op.drop_index(op.f('ix_collection_jobs_source_id'), table_name='collection_jobs')
    op.drop_index(op.f('ix_collection_jobs_run_configuration_id'), table_name='collection_jobs')
    op.drop_index(op.f('ix_collection_jobs_platform'), table_name='collection_jobs')
    op.drop_index(op.f('ix_collection_jobs_connection_id'), table_name='collection_jobs')
    op.drop_table('collection_jobs')
    op.drop_index(op.f('ix_run_configurations_user_id'), table_name='run_configurations')
    op.drop_index(op.f('ix_run_configurations_source_id'), table_name='run_configurations')
    op.drop_index(op.f('ix_run_configurations_is_archived'), table_name='run_configurations')
    op.drop_index(op.f('ix_run_configurations_connection_id'), table_name='run_configurations')
    op.drop_table('run_configurations')
    op.drop_index(op.f('ix_oauth_states_user_id'), table_name='oauth_states')
    op.drop_index(op.f('ix_oauth_states_state_hash'), table_name='oauth_states')
    op.drop_index(op.f('ix_oauth_states_provider'), table_name='oauth_states')
    op.drop_index(op.f('ix_oauth_states_expires_at'), table_name='oauth_states')
    op.drop_index(op.f('ix_oauth_states_connection_id'), table_name='oauth_states')
    op.drop_table('oauth_states')
    op.drop_index(op.f('ix_platform_connections_user_id'), table_name='platform_connections')
    op.drop_index(op.f('ix_platform_connections_status'), table_name='platform_connections')
    op.drop_index(op.f('ix_platform_connections_platform'), table_name='platform_connections')
    op.drop_table('platform_connections')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_token_hash'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_expires_at'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_sources_platform_kind_enabled', table_name='sources')
    op.drop_index(op.f('ix_sources_platform'), table_name='sources')
    op.drop_index(op.f('ix_sources_handle'), table_name='sources')
    op.drop_index(op.f('ix_sources_external_id'), table_name='sources')
    op.drop_index(op.f('ix_sources_authorization_status'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_social_accounts_username'), table_name='social_accounts')
    op.drop_index(op.f('ix_social_accounts_platform'), table_name='social_accounts')
    op.drop_index(op.f('ix_social_accounts_external_id'), table_name='social_accounts')
    op.drop_index(op.f('ix_social_accounts_account_hash'), table_name='social_accounts')
    op.drop_table('social_accounts')
    # ### end Alembic commands ###
